import type { LucideIcon } from 'lucide-react';
import {
  CaseSensitive,
  Braces,
  Palette,
  Lock,
  QrCode,
  Image as ImageIcon,
  Bot,
  Star,
  FileJson,
  Scale,
  DollarSign,
  Quote,
  Sparkles,
  Contrast,
  Tags,
  Hash,
  Fingerprint,
  Languages,
  BookType,
  Mic,
  ArrowRightLeft,
  Crop,
  PenSquare,
  UserRound,
  ClipboardCheck,
  ClipboardList,
  Lightbulb,
  Gamepad2,
  Film,
  ChefHat,
  BrainCircuit,
  Plane,
  RectangleHorizontal,
  Wallet,
  ShoppingCart,
  Wrench,
  Cloud,
} from 'lucide-react';

export type Tool = {
  name: string;
  slug: string;
  description: string;
  icon: LucideIcon;
  category: string;
  isAi?: boolean;
  href?: string;
};

export const tools: Tool[] = [
  {
    name: 'Text Case Converter',
    slug: 'text-case-converter',
    description: 'Convert text to various cases like uppercase, lowercase, etc.',
    icon: CaseSensitive,
    category: 'Text',
  },
  {
    name: 'Unit Converter',
    slug: 'unit-converter',
    description: 'Convert between different units of measurement.',
    icon: Scale,
    category: 'Generators',
  },
  {
    name: 'JSON Formatter',
    slug: 'json-formatter',
    description: 'Format, validate, and beautify your JSON data.',
    icon: Braces,
    category: 'Code',
  },
  {
    name: 'Code Formatter',
    slug: 'code-formatter',
    description: 'Beautify or minify your HTML, CSS, and JavaScript code.',
    icon: FileJson,
    category: 'Code',
  },
  {
    name: 'Markdown to HTML',
    slug: 'markdown-to-html',
    description: 'Convert Markdown text into HTML markup.',
    icon: BookType,
    category: 'Code',
  },
  {
    name: 'JWT Decoder',
    slug: 'jwt-decoder',
    description: 'Decode and inspect JSON Web Tokens in your browser.',
    icon: Fingerprint,
    category: 'Developer',
  },
  {
    name: 'Color Palette Generator',
    slug: 'color-palette-generator',
    description: 'Create beautiful color palettes with AI.',
    icon: Palette,
    category: 'Design',
    isAi: true,
  },
  {
    name: 'Color Contrast Checker',
    slug: 'color-contrast-checker',
    description: 'Check color contrast against WCAG guidelines.',
    icon: Contrast,
    category: 'Design',
  },
  {
    name: 'Password Generator',
    slug: 'password-generator',
    description: 'Generate strong, secure, and random passwords.',
    icon: Lock,
    category: 'Generators',
  },
  {
    name: 'QR Code Generator',
    slug: 'qr-code-generator',
    description: 'Create QR codes for URLs, text, and more.',
    icon: QrCode,
    category: 'Generators',
  },
  {
    name: 'Name Generator',
    slug: 'name-generator',
    description: 'Generate random usernames and startup names.',
    icon: Sparkles,
    category: 'Generators',
  },
  {
    name: 'Quote Generator',
    slug: 'quote-generator',
    description: 'Get a random quote to inspire you.',
    icon: Quote,
    category: 'Generators',
  },
  {
    name: 'Currency Converter',
    slug: 'currency-converter',
    description: 'Convert currencies using real-time exchange rates.',
    icon: DollarSign,
    category: 'Generators',
  },
  {
    name: 'Language Translator',
    slug: 'language-translator',
    description: 'Translate text between different languages using AI.',
    icon: Languages,
    category: 'AI',
    isAi: true,
  },
  {
    name: 'Text to Speech',
    slug: 'text-to-speech',
    description: 'Convert text to speech using browser APIs.',
    icon: Mic,
    category: 'AI',
    isAi: true,
  },
  {
    name: 'Image Compressor',
    slug: 'image-compressor',
    description: 'Compress JPG, PNG, and WEBP images client-side.',
    icon: ImageIcon,
    category: 'Image',
  },
  {
    name: 'Image Resizer',
    slug: 'image-resizer',
    description: 'Resize and crop your images in the browser.',
    icon: Crop,
    category: 'Image',
  },
  {
    name: 'JPEG Compressor',
    slug: 'jpeg-compressor',
    description: 'Compress JPEG images to reduce file size.',
    icon: FileJson,
    category: 'Image',
  },
  {
    name: 'Meta Tag Generator',
    slug: 'meta-tag-generator',
    description: 'Generate meta tags for your website for better SEO.',
    icon: Tags,
    category: 'Developer',
  },
  {
    name: 'UUID Generator',
    slug: 'uuid-generator',
    description: 'Generate universally unique identifiers (UUIDs).',
    icon: Hash,
    category: 'Developer',
  },
  {
    name: 'CashPilot',
    slug: 'cash-pilot',
    description: 'A mini finance dashboard to pilot your cash.',
    icon: Wallet,
    category: 'Finance',
  },
  {
    name: 'AI Humanizer',
    slug: 'ai-humanizer',
    description: 'Make AI-generated text sound more human.',
    icon: UserRound,
    category: 'AI',
    isAi: true,
  },
  {
    name: 'AI Rewriter & Summarizer',
    slug: 'ai-rewriter',
    description: 'Rewrite, rephrase, or summarize your text.',
    icon: PenSquare,
    category: 'AI',
    isAi: true,
  },
  {
    name: 'Originality Checker',
    slug: 'originality-checker',
    description: 'Check for plagiarism and originality in your text.',
    icon: ClipboardCheck,
    category: 'AI',
    isAi: true,
  },
  {
    name: 'AI Prompt Rewriter',
    slug: 'ai-prompt-rewriter',
    description: 'Improve your AI prompts for better results.',
    icon: Lightbulb,
    category: 'AI',
    isAi: true,
  },
  {
    name: 'Code Assistant',
    slug: 'code-assistant',
    description: 'Get explanations, error checks, and suggestions for your code.',
    icon: Bot,
    category: 'AI',
    isAi: true,
  },
  {
    name: 'AI Recipe Generator',
    slug: 'ai-recipe-generator',
    description: 'Generate recipes from the ingredients you have.',
    icon: ChefHat,
    category: 'AI',
    isAi: true,
  },
  {
    name: 'AI Topic Explainer',
    slug: 'ai-topic-explainer',
    description: 'Understand complex topics with simple explanations.',
    icon: BrainCircuit,
    category: 'AI',
    isAi: true,
  },
  {
    name: 'AI Trip Planner',
    slug: 'ai-trip-planner',
    description: 'Create a personalized travel itinerary in seconds.',
    icon: Plane,
    category: 'AI',
    isAi: true,
  },
  {
    name: 'Meeting Notes Summarizer',
    slug: 'meeting-notes',
    description: 'Turn messy transcripts into actionable recaps with decisions and tasks.',
    icon: ClipboardList,
    category: 'AI',
    isAi: true,
  },
  {
    name: 'Smart Shopping List',
    slug: 'smart-shopping-list',
    description: 'Build a budget-aware grocery plan with nutrition and meal prep tips.',
    icon: ShoppingCart,
    category: 'AI',
    isAi: true,
  },
  {
    name: 'DIY Fix Guide',
    slug: 'diy-fix-guide',
    description: 'Diagnose household issues and get a safe, step-by-step repair walkthrough.',
    icon: Wrench,
    category: 'AI',
    isAi: true,
  },
  {
    name: 'Pac-Man',
    slug: 'pacman',
    description: 'Play a classic arcade game.',
    icon: Gamepad2,
    category: 'Games',
  },
  {
    name: 'Breakout',
    slug: 'breakout',
    description: 'A classic brick-breaking arcade game.',
    icon: RectangleHorizontal,
    category: 'Games',
  },
  {
    name: 'Junycast',
    slug: 'junycast',
    description: 'Weather app — opens in a new tab.',
    icon: Cloud,
    category: 'Weather Forecast',
    href: 'https://junycast.vercel.app/',
  },
];

export const toolCategories = [
  'AI',
  'Text',
  'Code',
  'Design',
  'Weather Forecast',
  'Finance',
  'Generators',
  'Image',
  'Developer',
  'Games',
];
